# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Location', max_length=30)),
                ('lat', models.DecimalField(db_column='latitude', decimal_places=8, max_digits=10)),
                ('lon', models.DecimalField(db_column='longitude', decimal_places=8, max_digits=11)),
            ],
            options={
                'db_table': 'beaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='densities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Location', max_length=30)),
                ('date', models.DateField(db_column='Date')),
                ('total', models.IntegerField(db_column='total')),
                ('length', models.DecimalField(db_column='length', decimal_places=2, max_digits=5)),
                ('density', models.DecimalField(db_column='density', decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Location', max_length=30)),
                ('date', models.DateField(db_column='Date')),
                ('chem', models.IntegerField(db_column='Chemicals')),
                ('textile', models.IntegerField(db_column='Cloth')),
                ('ceramic', models.IntegerField(db_column='Glass')),
                ('metal', models.IntegerField(db_column='Metal')),
                ('paper', models.IntegerField(db_column='Paper')),
                ('plastic', models.IntegerField(db_column='Plastic')),
                ('rubber', models.IntegerField(db_column='Rubber')),
                ('other', models.IntegerField(db_column='Unidentified')),
                ('wood', models.IntegerField(db_column='Wood')),
                ('total', models.IntegerField(db_column='Total')),
            ],
        ),
    ]
