# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='densities',
        ),
        migrations.DeleteModel(
            name='material',
        ),
    ]
