# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0002_auto_20171203_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_column='code', max_length=5, null=True)),
                ('material', models.CharField(blank=True, db_column='material', max_length=30, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=30, null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=30, null=True)),
            ],
            options={
                'db_table': 'codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Densities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=30, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('total', models.IntegerField(blank=True, db_column='total', null=True)),
                ('length', models.IntegerField(blank=True, db_column='length', null=True)),
                ('density', models.DecimalField(blank=True, db_column='density', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'densities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=30, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('chemicals', models.IntegerField(blank=True, db_column='Chemicals', null=True)),
                ('cloth', models.IntegerField(blank=True, db_column='Cloth', null=True)),
                ('glass', models.IntegerField(blank=True, db_column='Glass', null=True)),
                ('metal', models.IntegerField(blank=True, db_column='Metal', null=True)),
                ('paper', models.IntegerField(blank=True, db_column='Paper', null=True)),
                ('plastic', models.IntegerField(blank=True, db_column='Plastic', null=True)),
                ('rubber', models.IntegerField(blank=True, db_column='Rubber', null=True)),
                ('unidentified', models.IntegerField(blank=True, db_column='Unidentified', null=True)),
                ('wood', models.IntegerField(blank=True, db_column='Wood', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=30, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('construction', models.IntegerField(blank=True, db_column='Construction', null=True)),
                ('fishing', models.IntegerField(blank=True, db_column='Fishing', null=True)),
                ('food', models.IntegerField(blank=True, db_column='Food', null=True)),
                ('fragment', models.IntegerField(blank=True, db_column='Fragment', null=True)),
                ('household', models.IntegerField(blank=True, db_column='Household', null=True)),
                ('industry', models.IntegerField(blank=True, db_column='Industry', null=True)),
                ('medical', models.IntegerField(blank=True, db_column='Medical', null=True)),
                ('other', models.IntegerField(blank=True, db_column='Other', null=True)),
                ('personal', models.IntegerField(blank=True, db_column='Personal', null=True)),
                ('recreation', models.IntegerField(blank=True, db_column='Recreation', null=True)),
                ('tobaco', models.IntegerField(blank=True, db_column='Tobaco', null=True)),
                ('water_treament', models.IntegerField(blank=True, db_column='Water_treament', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
