# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0003_codes_densities_material_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='densities',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': True},
        ),
    ]
