# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 06:32
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0004_auto_20171204_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('length', models.DecimalField(blank=True, db_column='length', decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'all_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('entry', models.CharField(choices=[('ex', 'expense'), ('re', 'revenue')], db_column='type', max_length=30)),
                ('origin', models.CharField(choices=[('t', 'Transportation'), ('m', 'Meals'), ('s', 'Software'), ('n', 'Network'), ('t', 'Telephone'), ('p', 'Personal equipment'), ('e', 'Equipment'), ('i', 'IT equipment'), ('o', 'Operations'), ('d', 'Donation'), ('s-g', 'Services group activity'), ('s-c', 'Services beach clean'), ('s-s', 'Services IT'), ('l', 'labor')], db_column='source', max_length=30)),
                ('amount', models.DecimalField(blank=True, db_column='amount', decimal_places=2, max_digits=10, null=True)),
                ('project', models.CharField(blank=True, db_column='project', max_length=30)),
            ],
            options={
                'db_table': 'finance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='title', max_length=240, null=True)),
                ('author', models.CharField(blank=True, db_column='author', max_length=120, null=True)),
                ('abstract', models.CharField(blank=True, db_column='abstract', max_length=300, null=True)),
                ('subject', models.CharField(choices=[('env', 'Environment - general'), ('env-h', 'Hydrology'), ('env-j', 'Environment - justice'), ('wat-q', 'Water quality'), ('bio', 'Biology - general'), ('chem', 'Chemistry'), ('m-bio', 'Microbiology'), ('b-l', 'Beach-litter'), ('econ', 'Economics'), ('cit', 'Citizen science'), ('gv', 'Government - reg'), ('mt', 'Math - general'), ('ma', 'Math - Analysis'), ('mp', 'Math - probability'), ('pp', 'Programing - python'), ('pd', 'Data science'), ('po', 'Programing - other'), ('gc', 'General culture')], db_column='subject', max_length=30)),
            ],
            options={
                'db_table': 'library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('code', models.CharField(db_column='mlw', max_length=30, primary_key=True, serialize=False)),
                ('Arabie', models.IntegerField(blank=True, db_column='Arabie', null=True)),
                ('Bain_des_Dames', models.IntegerField(blank=True, db_column='Bain_des_Dames', null=True)),
                ('Baye_de_Clarens', models.IntegerField(blank=True, db_column='Baye_de_Clarens', null=True)),
                ('Baye_de_Montreux_D', models.IntegerField(blank=True, db_column='Baye_de_Montreux_D', null=True)),
                ('Baye_de_Montreux_G', models.IntegerField(blank=True, db_column='Baye_de_Montreux_G', null=True)),
                ('Boiron', models.IntegerField(blank=True, db_column='Boiron', null=True)),
                ('Grand_Clos', models.IntegerField(blank=True, db_column='Grand_Clos', null=True)),
                ('Jardin_Botanique', models.IntegerField(blank=True, db_column='Jardin_Botanique', null=True)),
                ('La_Morges', models.IntegerField(blank=True, db_column='La_Morges', null=True)),
                ('Le_Pierrier', models.IntegerField(blank=True, db_column='Le_Pierier', null=True)),
                ('Le_Port', models.IntegerField(blank=True, db_column='Le_Port', null=True)),
                ('Maladaire', models.IntegerField(blank=True, db_column='Maladaire', null=True)),
                ('Oyonne', models.IntegerField(blank=True, db_column='Oyonne', null=True)),
                ('Parc_des_Pierrettes', models.IntegerField(blank=True, db_column='Parc_des_Pierrettes', null=True)),
                ('Pierrier_sud', models.IntegerField(blank=True, db_column='Pierier_sud', null=True)),
                ('Plage_de_Dorigny', models.IntegerField(blank=True, db_column='Plage_de_Dorigny', null=True)),
                ('Plage_de_St_Sulpice', models.IntegerField(blank=True, db_column='Plage_de_St_Sulpice', null=True)),
                ('Quai_Maria_Belgia', models.IntegerField(blank=True, db_column='Quai_Maria_Belgia', null=True)),
                ('Thonnon_les_Bains', models.IntegerField(blank=True, db_column='Thonnon_les_Bains', null=True)),
                ('Versoix', models.IntegerField(blank=True, db_column='Versoix', null=True)),
                ('Veveyse', models.IntegerField(blank=True, db_column='Veveyse', null=True)),
                ('Vidy', models.IntegerField(blank=True, db_column='Vidy', null=True)),
                ('Villa_Barton', models.IntegerField(blank=True, db_column='Villa_Barton', null=True)),
            ],
            options={
                'db_table': 'codes_totals',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='beaches',
            options={'managed': False, 'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='codes',
            options={'managed': False, 'ordering': ['material']},
        ),
        migrations.AlterModelOptions(
            name='densities',
            options={'managed': False, 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False, 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': False, 'ordering': ['Date']},
        ),
        migrations.AlterModelManagers(
            name='source',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='construction',
            new_name='Construction',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='fishing',
            new_name='Fishing',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='food',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='fragment',
            new_name='Fragment',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='household',
            new_name='Household',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='industry',
            new_name='Industry',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='medical',
            new_name='Medical',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='other',
            new_name='Other',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='personal',
            new_name='Personal',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='recreation',
            new_name='Recreation',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='tobaco',
            new_name='Tobaco',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='water_treament',
            new_name='Water_treatment',
        ),
    ]
