# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0005_auto_20180210_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLR_Beaches',
            fields=[
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'slr_beaches',
                'ordering': ['location'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SLR_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('length', models.DecimalField(blank=True, db_column='length', decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='quantity', decimal_places=2, max_digits=7, null=True)),
                ('density', models.DecimalField(blank=True, db_column='density', decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'slr_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Try_this',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('dirt.all_data',),
        ),
        migrations.AlterModelOptions(
            name='densities',
            options={'managed': True, 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': True, 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'managed': True, 'ordering': ['Date']},
        ),
        migrations.AlterModelOptions(
            name='totals',
            options={'managed': True},
        ),
    ]
