# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0006_auto_20180214_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLR_Density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
                ('density', models.DecimalField(blank=True, db_column='density', decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'slr_dens_date',
                'managed': False,
            },
        ),
    ]
