# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0007_slr_density'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beaches',
            options={'managed': True, 'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='slr_beaches',
            options={'managed': True, 'ordering': ['location']},
        ),
    ]
