# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0008_auto_20180224_0720'),
    ]

