# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirt', '0011_auto_20180224_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beaches',
            options={'managed': False, 'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='slr_beaches',
            options={'managed': False, 'ordering': ['location']},
        ),
    ]
