# Generated by Django 2.0.2 on 2018-09-02 22:05

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('location', models.CharField(db_column='location', max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=8, max_digits=11)),
                ('city', models.CharField(db_column='city', default='city', max_length=100)),
                ('post', models.CharField(db_column='post', default='post code', max_length=12)),
                ('departement', models.IntegerField(db_column='length', default=0)),
                ('water', models.CharField(choices=[('r', 'river'), ('l', 'lake'), ('o', 'ocean')], db_column='water', default='o', max_length=12)),
                ('water_name', models.CharField(db_column='water_name', default='name of water body', max_length=100)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beach',
                'ordering': ['location'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('m_code', models.CharField(db_column='m_code', max_length=5, primary_key=True, serialize=False, verbose_name='MLW code')),
                ('o_code', models.CharField(db_column='o_code', max_length=5, verbose_name='OSPAR code')),
                ('material', models.CharField(db_column='material', default='plastic', max_length=30)),
                ('description', models.CharField(db_column='description', default='trash', max_length=30)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'code',
                'ordering': ['material'],
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('length', models.IntegerField(db_column='length', default=0)),
                ('method', models.CharField(choices=[('i', 'inventory'), ('w', 'weight'), ('v', 'volume'), ('w-v', 'weght and volume')], db_column='method', default='i', max_length=12)),
                ('volume', models.IntegerField(db_column='volume', default=0)),
                ('weight', models.DecimalField(db_column='weight', decimal_places=2, default=0, max_digits=6, verbose_name='weight in kilos')),
                ('time', models.IntegerField(db_column='time', default=0, verbose_name='time in minutes')),
                ('people', models.IntegerField(db_column='people', default=0, verbose_name='number of people')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Beach')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('length', models.IntegerField(db_column='length', default=0)),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('code', models.ForeignKey(db_column='code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Code')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Beach')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itemdata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project', models.CharField(db_column='project', max_length=100, primary_key=True, serialize=False)),
                ('org', models.CharField(db_column='org', default='project', max_length=100)),
                ('org_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='MerTerOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['project'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='itemdata',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Project'),
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Project'),
        ),
        migrations.AddField(
            model_name='beach',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.DO_NOTHING, to='merter.Project'),
        ),
    ]
