# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 03:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beach',
            options={'managed': True, 'ordering': ['location'], 'verbose_name_plural': 'Mer-Terre Beaches'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'managed': True, 'ordering': ['material'], 'verbose_name_plural': 'Mer-Terre Codes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True, 'verbose_name_plural': 'Mer-Terre Surveys'},
        ),
        migrations.AlterModelOptions(
            name='itemdata',
            options={'managed': True, 'verbose_name_plural': 'Mer-Terre Objects'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'ordering': ['project'], 'verbose_name_plural': 'Mer-Terre Projects'},
        ),
        migrations.AlterField(
            model_name='beach',
            name='latitude',
            field=models.DecimalField(db_column='latitude', decimal_places=8, default=11.1111, max_digits=11),
        ),
        migrations.AlterField(
            model_name='beach',
            name='location',
            field=models.CharField(db_column='location', default='beach name', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beach',
            name='longitude',
            field=models.DecimalField(db_column='longitude', decimal_places=8, default=11.1111, max_digits=11),
        ),
        migrations.AlterField(
            model_name='beach',
            name='water',
            field=models.CharField(choices=[('r', 'river'), ('l', 'lake'), ('o', 'ocean')], db_column='water', default='ocean', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='org',
            field=models.CharField(db_column='org', default='organisation', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='org_email',
            field=models.EmailField(default='you@yoursite.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(db_column='project', default='project', max_length=100, primary_key=True, serialize=False),
        ),
    ]
