# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merter', '0002_auto_20180903_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.CharField(db_column='description', default='trash', max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='material',
            field=models.CharField(db_column='material', default='plastic', max_length=60),
        ),
    ]
