# Generated by Django 2.0.2 on 2018-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merter', '0003_auto_20180903_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='material',
            field=models.CharField(db_column='material', default='plastic', max_length=100),
        ),
    ]
