# Generated by Django 2.0.2 on 2018-09-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merter', '0004_auto_20180905_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='owner',
        ),
    ]
