# Generated by Django 2.0.2 on 2018-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merter', '0005_remove_code_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='description',
            field=models.CharField(db_column='description', default='trash', max_length=140),
        ),
    ]
